server:
  port: 80

spring:
  application:
    name: order-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001-server:7001/eureka,http://eureka7002-server:7002/eureka